<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXO01aiD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXO01aiD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXO01aiD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXO01aiD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXO01aiD\App_KernelDevDebugContainer([
    'container.build_hash' => 'XO01aiD',
    'container.build_id' => '81f0c100',
    'container.build_time' => 1774987442,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXO01aiD');
