<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHNbxiCS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHNbxiCS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHNbxiCS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHNbxiCS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHNbxiCS\App_KernelDevDebugContainer([
    'container.build_hash' => 'HNbxiCS',
    'container.build_id' => 'e000bba0',
    'container.build_time' => 1775065858,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHNbxiCS');
