<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_a2a' => [[], ['_controller' => 'App\\Controller\\Api\\A2AController'], [], [['text', '/api/v1/a2a']], [], [], []],
    'api_manifest' => [[], ['_controller' => 'App\\Controller\\Api\\ManifestController'], [], [['text', '/api/v1/manifest']], [], [], []],
    'health' => [[], ['_controller' => 'App\\Controller\\HealthController::health'], [], [['text', '/health']], [], [], []],
    'App\Controller\Api\A2AController::__invoke' => [[], ['_controller' => 'App\\Controller\\Api\\A2AController'], [], [['text', '/api/v1/a2a']], [], [], []],
    'App\Controller\Api\A2AController' => [[], ['_controller' => 'App\\Controller\\Api\\A2AController'], [], [['text', '/api/v1/a2a']], [], [], []],
    'App\Controller\Api\ManifestController::__invoke' => [[], ['_controller' => 'App\\Controller\\Api\\ManifestController'], [], [['text', '/api/v1/manifest']], [], [], []],
    'App\Controller\Api\ManifestController' => [[], ['_controller' => 'App\\Controller\\Api\\ManifestController'], [], [['text', '/api/v1/manifest']], [], [], []],
    'App\Controller\HealthController::health' => [[], ['_controller' => 'App\\Controller\\HealthController::health'], [], [['text', '/health']], [], [], []],
];
