<?php

namespace ContainerXO01aiD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getA2AControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\A2AController' shared autowired service.
     *
     * @return \App\Controller\Api\A2AController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/A2AController.php';
        include_once \dirname(__DIR__, 4).'/src/A2A/TelegramChannelA2AHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Telegram/TelegramApiClient.php';
        include_once \dirname(__DIR__, 4).'/src/Telegram/TelegramSender.php';
        include_once \dirname(__DIR__, 4).'/src/Telegram/TelegramNormalizer.php';

        $a = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        $b = new \App\Telegram\TelegramApiClient($a);

        $container->services['App\\Controller\\Api\\A2AController'] = $instance = new \App\Controller\Api\A2AController(new \App\A2A\TelegramChannelA2AHandler($b, new \App\Telegram\TelegramSender($b, $a), new \App\Telegram\TelegramNormalizer(), $a, $container->getEnv('PIPELINE_TASKS_ROOT'), $container->getEnv('FOUNDRY_SH'), $container->getEnv('PIPELINE_TELEGRAM_CHAT_ID'), $container->getEnv('PIPELINE_TELEGRAM_ALLOWED_USERS')), $a);

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\A2AController', $container));

        return $instance;
    }
}
