#!/usr/bin/env bash
#
# Mock agent for E2E testing.
# Simulates quick agent execution without calling real LLMs.
#
set -euo pipefail

AGENT_NAME="${1:-unknown}"
TASK_FILE="${2:-}"
OUTPUT_DIR="${3:-.}"

# Simulate agent work (1-2 seconds)
sleep 1

case "$AGENT_NAME" in
  u-coder)
    # Create a simple test file
    cat > "$OUTPUT_DIR/test-file.txt" <<EOF
# Test file created by mock u-coder agent

This is a test file created during E2E testing.
Task: $(head -1 "$TASK_FILE" | sed 's/^# //')
EOF
    echo "✓ Mock u-coder: Created test-file.txt"
    ;;

  u-validator)
    # Simulate validation checks
    echo "✓ Mock u-validator: All checks passed"
    ;;

  u-tester)
    # Simulate running tests
    echo "✓ Mock u-tester: All tests passed"
    ;;

  u-summarizer)
    # Create summary
    cat > "$OUTPUT_DIR/summary.md" <<EOF
# Task Summary (Mock)

**Status**: Completed successfully ✅

## Changes Made
- Created test-file.txt
- All validations passed
- All tests passed

## Verification
- [x] File created
- [x] Validation checks passed
- [x] Tests executed

---
*This summary was generated by mock E2E agent for testing purposes.*
EOF
    echo "✓ Mock u-summarizer: Created summary.md"
    ;;

  *)
    echo "✓ Mock $AGENT_NAME: No-op agent (testing)"
    ;;
esac

exit 0
