apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: brama
  labels:
    app.kubernetes.io/part-of: brama
    app.kubernetes.io/component: infra
    app.kubernetes.io/name: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
